## 异常总结
```
/**
 * 异常处理的方式一：
 * 
 * java.lang.Throwable |---Error：错误，程序中不进行处理
 * |---Exception：异常，要求在编写程序时，就要考虑对这些异常的处理
 * |---编译时异常，在编译期间会出现的异常（执行javac.exe命令时，出现的异常）
 * |---运行时异常，在运行期间出现的异常（执行java.exe命令时，出现的异常）
 * 
 * 处理Exception的异常，Java提供的是异常处理的抓抛模型
 * 1. “抛”：当我们执行代码时，一旦出现异常，就会在异常的代码处生成一个对应的异常类对象，并将此对象抛出（自动抛出/手动抛出）
 *          > 一旦抛出此类的异常对象，那么程序就终止执行
 *          > 此异常类的对象抛给方法调用者
 * 2. “抓”：抓住上一步抛出此类的对象，那么程序就终止执行。
 *    Java提供了2种方式用来处理一个异常的对象
 *     处理方式一：
 *          try{
 *            // 可能出现异常的代码
 *          } catch(Exception e1) {
 *            // 处理方式1
 *          } finally {
 *             //  一定要执行的代码，可选
 *           }
 *    注：1. try内声明的变量，类似于局部变量，出了try{}语句，就不能被调用
 *        2. finally是可选的
 *        3. catch语句内部是对异常对象的处理
 *            > e.getMessage();  出现问题的异常信息
 *            > e.printStackTree();  堆栈的详细信息，表明问题出现的原因
 *        4. 可以有多个catch语句，try中抛出的异常类对象从上往下去匹配catch中的异常类型
 *                一旦满足就执行catch中的语句。执行完，就跳出其后的多条catch语句
 *        5. 如果异常处理了，那么其后的代码就可以执行
 *        6. 若catch中多个异常类型是“并列”关系，孰上孰下都可以
 *           若catch中多个异常类型是不“包含”关系，须将子类放在父类的上面，进行处理，否则报错
 *        7. finally中存放的是一定会被执行的代码，不管try中，catch中是否仍然有异常未被处理，以及是否有return语句
 *        8. try-catch是可以相互嵌套的
 * 
 * 3. 对于运行时的异常，可以不显示的进行处理
 *      对于编译时的异常，必须要显示的进行处理
 * 
 *     try-catch-finally 都有return，那么出现异常的时候，return的是finally里的热土让你
 *        如果finally没有return，catch里面有return，那么返回的catch语句块里return，但是在块外面的语句不能执行，会报错
 * 
 * 异常处理的方式二：(throws)
 *   1. throws 方法抛出异常的声明，用在声明方法时，
 *       格式：public void doA(int a) throws Exception1,Exception3{......}
 *       可以一致向上抛，直至main方法，最后给JVM。也可以通过try-catch-finally来处理
 * 
 * 异常处理的方式三：(throw)
 *   手动抛出一个异常对象，如果是运行时异常，可不显示处理；如果是编译时异常需要显示处理
 *   throw单独存在（如不依赖if）如果后面跟语句，编译报错
 * 
 * 自定义异常
 *   1. 一般继承RuntimeException，需要有serialVersionUID
 *   2. 子类重写父类的方法，抛出的异常类型只能是被重写的方法的异常类型的子类或和异常类型一致
 * 
 * 
 * 有return的情况下try catch finally的执行顺序
 * 结论：
 * 1、不管有没有出现异常，finally块中代码都会执行；
 * 2、当try和catch中有return时，finally仍然会执行；
 * 3、finally是在return后面的表达式运算后执行的（此时并没有返回运算后的值，而是先把要返回的值保存起来，不管finally中的代码怎么样，返回的值都不会改变，任然是之前保存的值），所以函数返回值是在finally执行前确定的；
 * 4、finally中最好不要包含return，否则程序会提前退出，返回值不是try或catch中保存的返回值。
 * 举例：
 * 情况1：try{} catch(){}finally{} return;
 *             显然程序按顺序执行。
 * 情况2:try{ return; }catch(){} finally{} return;
 *           程序执行try块中return之前（包括return语句中的表达式运算）代码；
 *          再执行finally块，最后执行try中return;
 *          finally块之后的语句return，因为程序在try中已经return所以不再执行。
 * 情况3:try{ } catch(){return;} finally{} return;
 *          程序先执行try，如果遇到异常执行catch块，
 *          有异常：则执行catch中return之前（包括return语句中的表达式运算）代码，再执行finally语句中全部代码，
 *                      最后执行catch块中return. finally之后也就是4处的代码不再执行。
 *          无异常：执行完try再finally再return.
 * 情况4:try{ return; }catch(){} finally{return;}
 *           程序执行try块中return之前（包括return语句中的表达式运算）代码；
 *           再执行finally块，因为finally块中有return所以提前退出。
 * 情况5:try{} catch(){return;}finally{return;}
 *           程序执行catch块中return之前（包括return语句中的表达式运算）代码；
 *           再执行finally块，因为finally块中有return所以提前退出。
 * 情况6:try{ return;}catch(){return;} finally{return;}
          程序执行try块中return之前（包括return语句中的表达式运算）代码；
          有异常：执行catch块中return之前（包括return语句中的表达式运算）代码；
                       则再执行finally块，因为finally块中有return所以提前退出。
          无异常：则再执行finally块，因为finally块中有return所以提前退出。

 * 最终结论：任何执行try 或者catch中的return语句之前，都会先执行finally语句，如果finally存在的话。
 *                   如果finally中有return语句，那么程序就return了，所以finally中的return是一定会被return的，
 *                   编译器把finally中的return实现为一个warning。
 */ 
```